using System;

namespace timeManager
{
    public class Calendar
    {
        private int currentDay;
        private int currentMonth;
        private int currentYear;
        private int selectedDay;
        private int daysInMonth;
        private int startDayIndex;
        private int selectedRowIndex;
        private int selectedColumnIndex;

        public Calendar()
        {
            currentDay = DateTime.Now.Day;
            currentMonth = DateTime.Now.Month;
            currentYear = DateTime.Now.Year;
            selectedDay = currentDay;
            daysInMonth = DateTime.DaysInMonth(currentYear, currentMonth);
            startDayIndex = (int)new DateTime(currentYear, currentMonth, 1).DayOfWeek;
            selectedRowIndex = (selectedDay + startDayIndex - 1) / 7;
            selectedColumnIndex = (selectedDay + startDayIndex - 1) % 7;
        }

        // TODO: Remake whole Print and HandleKeyPress methods,
        // they're too long and too much redundant code (generated by GPT-3.5)
        public void Print()
        {
            Console.WriteLine($" {DateTime.Now.ToString("MMMM yyyy")}");

            Console.WriteLine(" ┌───┬───┬───┬───┬───┬───┬───┐");
            Console.WriteLine(" │ Mo│ Tu│ We│ Th│ Fr│ Sa│ Su│");
            Console.WriteLine(" ├───┼───┼───┼───┼───┼───┼───┤");

            for (int i = 0; i < 5; i++)
            {
                Console.Write(" ");

                for (int j = 0; j < 7; j++)
                {
                    int day = i * 7 + j + 1 - startDayIndex;
                    if (day <= 0 || day > daysInMonth)
                    {
                        Console.Write("│   ");
                    }
                    else
                    {
                        Console.Write("│");

                        if (day == selectedDay)
                        {
                            Console.BackgroundColor = ConsoleColor.White;
                            Console.ForegroundColor = ConsoleColor.Black;
                        }
                        Console.Write($" {day,2}");

                        Console.ResetColor();
                    }
                }
                Console.WriteLine("│");
                if (i < 4)
                    Console.WriteLine(" ├───┼───┼───┼───┼───┼───┼───┤");
            }

            Console.WriteLine(" └───┴───┴───┴───┴───┴───┴───┘");

            Console.WriteLine("Press Q to exit");
        }

        /// <summary>
        /// Handle key press
        /// </summary>
        /// <param name="keyInfo"> Key info </param>
        public void HandleKeyPress(ConsoleKeyInfo keyInfo)
        {
            switch (keyInfo.Key)
            {
                case ConsoleKey.UpArrow:
                    if (selectedRowIndex > 0)
                    {
                        selectedRowIndex--;
                        selectedDay -= 7;
                    }

                    break;

                case ConsoleKey.DownArrow:
                    if (selectedRowIndex < 4 && selectedDay + 7 <= daysInMonth)
                    {
                        selectedRowIndex++;
                        selectedDay += 7;
                    }
                    break;

                case ConsoleKey.LeftArrow:
                    selectedColumnIndex = (selectedColumnIndex == 0) ? 6 : selectedColumnIndex - 1;
                    selectedDay = selectedRowIndex * 7 + selectedColumnIndex - startDayIndex + 1;
                    if (selectedDay <= 0)
                        selectedDay += daysInMonth;
                    break;

                case ConsoleKey.RightArrow:
                    selectedColumnIndex = (selectedColumnIndex == 6) ? 0 : selectedColumnIndex + 1;
                    selectedDay = selectedRowIndex * 7 + selectedColumnIndex - startDayIndex + 1;
                    if (selectedDay > daysInMonth)
                        selectedDay -= daysInMonth;
                    break;

                case ConsoleKey.Enter:
                    Console.WriteLine("TODO");
                    break;
            }
        }

        public static void Run()
        {
            Console.CursorVisible = false;
            var calendar = new Calendar();
            ConsoleKeyInfo keyInfo;
            do
            {
                Console.Clear();
                calendar.Print();
                keyInfo = Console.ReadKey(true);
                calendar.HandleKeyPress(keyInfo);
            } while (keyInfo.Key != ConsoleKey.Q);
        }
    }
}